name: Build and deploy Node.js app to Azure Web App - birthday

# Run the workflow whenever changes are pushed into the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production.
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        # Add other scripts here if configured, such as linting, formatting

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist # This should be your distribution path, not the root path

  # Deploy the application to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: birthday
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C69ADD2F4A3A4CA8807CB771985D8AAD }} # Publish profile should always be stored as secrets in your repository Settings - Secrets and variables - Actions - secrets
          package: ./dist # Ensure this path matches the built package directory
